// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYN7TC_tkU_EeoDPtrE3kr-e9UIpq3kg0',
    appId: '1:958383593165:web:c2e31cdae2fa1d02407b84',
    messagingSenderId: '958383593165',
    projectId: 'flutterapp-2cbaf',
    authDomain: 'flutterapp-2cbaf.firebaseapp.com',
    storageBucket: 'flutterapp-2cbaf.appspot.com',
    measurementId: 'G-XKT29834EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy_Pid85vnrJZAN1ETfnpuUOT74Dreb7Q',
    appId: '1:958383593165:android:2d8463ba2d285102407b84',
    messagingSenderId: '958383593165',
    projectId: 'flutterapp-2cbaf',
    storageBucket: 'flutterapp-2cbaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgNg9C8fPN9zgk7wI6ECK_Kl3CeFVmRdw',
    appId: '1:958383593165:ios:9344412f296e1d4d407b84',
    messagingSenderId: '958383593165',
    projectId: 'flutterapp-2cbaf',
    storageBucket: 'flutterapp-2cbaf.appspot.com',
    iosClientId: '958383593165-6nqei1tqbdfn9kmjsqijfe2ko4qe1k8k.apps.googleusercontent.com',
    iosBundleId: 'com.learnflutter.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgNg9C8fPN9zgk7wI6ECK_Kl3CeFVmRdw',
    appId: '1:958383593165:ios:9344412f296e1d4d407b84',
    messagingSenderId: '958383593165',
    projectId: 'flutterapp-2cbaf',
    storageBucket: 'flutterapp-2cbaf.appspot.com',
    iosClientId: '958383593165-6nqei1tqbdfn9kmjsqijfe2ko4qe1k8k.apps.googleusercontent.com',
    iosBundleId: 'com.learnflutter.flutterapp',
  );
}
